### PR TITLE
fix cannot delete roles & fix cannot add point based package rules

### PR DESCRIPTION
**Pull request by liuzhen**
currently it cannot delete role from role list page.
cannot add point base package rule due to lacking to type conversion.

### CODE REVIEW

**Comment by Licenser** [comment]
This is a bit more complicated, the value needs to be a number in the end, transmitting `"1"` will make a rule that is defunct if ti works at all.

I think the problem snuck in because option transforms the `value` attribute into a string. Re-reading the file the right fix seems to be to change the `->state` in line 104 into something that transforms the data aproprately (either leave it as must/cant/scale/random or parses it into a number.

**Comment by liuzhen** [comment]
I get it, i have only fixed the button problem but no the rule itself.
I will update as you said.

**Comment by liuzhen** [comment]
It's beyond be to change `->state`.
Not ok if both change line 44 & line 65?

**Comment by Licenser** [comment]
Thanks mate!

**Pull request merged**
